export const SUGGESTED_QUESTIONS = [
  "¿Qué es la Universidad Autónoma de Santo Domingo?",
  "¿Cuál es la misión de la UASD?",
  "¿Cuáles son los fines de la Universidad?",
  "¿Cuáles son las funciones fundamentales de la UASD?",
  "¿Qué establece el Estatuto sobre la autonomía universitaria?",
  "¿Cuáles son los principios que orientan a la Universidad?",
  "¿Cómo está organizada la Universidad?",
  "¿Cuáles son los organismos de gobierno de la UASD?",
  "¿Qué es el Claustro Mayor?",
  "¿Qué es el Claustro Menor?",
  "¿Qué es el Consejo Universitario?",
  "¿Quiénes integran el Consejo Universitario?",
  "¿Cuáles son las atribuciones del Consejo Universitario?",
  "¿Cuáles son las funciones del Rector?",
  "¿Cuáles son las funciones de los Vicerrectores?",
  "¿Qué son las Facultades?",
  "¿Cómo se organizan las Facultades?",
  "¿Qué son los Consejos Directivos de Facultad?",
  "¿Cuáles son las funciones de los Decanos?",
  "¿Qué son las Escuelas?",
  "¿Cuáles son las funciones de los Directores de Escuela?",
  "¿Qué establece el Estatuto sobre los Recintos, Centros y Subcentros Universitarios?",
  "¿Qué establece el Estatuto sobre el personal docente?",
  "¿Cuáles son los derechos del personal docente?",
  "¿Cuáles son los deberes del personal docente?",
  "¿Qué establece el Estatuto sobre los estudiantes?",
  "¿Cuáles son los derechos de los estudiantes?",
  "¿Cuáles son los deberes de los estudiantes?",
  "¿Qué establece el Estatuto sobre la representación estudiantil?",
  "¿Qué establece el Estatuto sobre la investigación?",
  "¿Qué establece el Estatuto sobre el postgrado?",
  "¿Qué establece el Estatuto sobre la extensión universitaria?",
  "¿Qué establece el Estatuto sobre el bienestar universitario?",
  "¿Qué establece el Estatuto sobre el régimen disciplinario?",
  "¿Qué establece el Estatuto sobre el patrimonio universitario?",
];

export const APP_NAME = "Chatbot UASD";
export const INSTITUTION_NAME = "Universidad Autónoma de Santo Domingo";
